#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 157
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  anon_sym_package = 1,
  anon_sym_LT = 2,
  anon_sym_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_EQ = 5,
  anon_sym_LBRACK = 6,
  anon_sym_COMMA = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COLON = 11,
  anon_sym_math = 12,
  anon_sym_SEMI = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_where = 16,
  anon_sym_otherwise = 17,
  anon_sym_STAR_STAR = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_PLUS = 21,
  anon_sym_DASH = 22,
  sym_identifier = 23,
  sym_number = 24,
  anon_sym_DQUOTE = 25,
  aux_sym_string_token1 = 26,
  anon_sym_SQUOTE = 27,
  aux_sym_string_token2 = 28,
  sym_comment = 29,
  sym_document = 30,
  sym__statement = 31,
  sym_package_statement = 32,
  sym_element = 33,
  sym_attribute = 34,
  sym__attribute_value = 35,
  sym_array = 36,
  sym_object = 37,
  sym_pair = 38,
  sym_value = 39,
  sym__content = 40,
  sym_math_block = 41,
  sym__math_content = 42,
  sym_math_expression_statement = 43,
  sym_math_expression = 44,
  sym_math_statement = 45,
  sym_math_function_definition = 46,
  sym_math_condition = 47,
  sym_math_term = 48,
  sym_identifier_list = 49,
  sym_imperative_block = 50,
  sym_imperative_statement = 51,
  sym_function_call = 52,
  sym_argument_list = 53,
  sym_string = 54,
  aux_sym_document_repeat1 = 55,
  aux_sym_element_repeat1 = 56,
  aux_sym_element_repeat2 = 57,
  aux_sym_array_repeat1 = 58,
  aux_sym_object_repeat1 = 59,
  aux_sym__math_content_repeat1 = 60,
  aux_sym_identifier_list_repeat1 = 61,
  aux_sym_imperative_block_repeat1 = 62,
  aux_sym_string_repeat1 = 63,
  aux_sym_string_repeat2 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_package] = "package",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_math] = "math",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_where] = "where",
  [anon_sym_otherwise] = "otherwise",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__statement] = "_statement",
  [sym_package_statement] = "package_statement",
  [sym_element] = "element",
  [sym_attribute] = "attribute",
  [sym__attribute_value] = "_attribute_value",
  [sym_array] = "array",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym_value] = "value",
  [sym__content] = "_content",
  [sym_math_block] = "math_block",
  [sym__math_content] = "_math_content",
  [sym_math_expression_statement] = "math_expression_statement",
  [sym_math_expression] = "math_expression",
  [sym_math_statement] = "math_statement",
  [sym_math_function_definition] = "math_function_definition",
  [sym_math_condition] = "math_condition",
  [sym_math_term] = "math_term",
  [sym_identifier_list] = "identifier_list",
  [sym_imperative_block] = "imperative_block",
  [sym_imperative_statement] = "imperative_statement",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [sym_string] = "string",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_element_repeat1] = "element_repeat1",
  [aux_sym_element_repeat2] = "element_repeat2",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym__math_content_repeat1] = "_math_content_repeat1",
  [aux_sym_identifier_list_repeat1] = "identifier_list_repeat1",
  [aux_sym_imperative_block_repeat1] = "imperative_block_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_math] = anon_sym_math,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_where] = anon_sym_where,
  [anon_sym_otherwise] = anon_sym_otherwise,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__statement] = sym__statement,
  [sym_package_statement] = sym_package_statement,
  [sym_element] = sym_element,
  [sym_attribute] = sym_attribute,
  [sym__attribute_value] = sym__attribute_value,
  [sym_array] = sym_array,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym_value] = sym_value,
  [sym__content] = sym__content,
  [sym_math_block] = sym_math_block,
  [sym__math_content] = sym__math_content,
  [sym_math_expression_statement] = sym_math_expression_statement,
  [sym_math_expression] = sym_math_expression,
  [sym_math_statement] = sym_math_statement,
  [sym_math_function_definition] = sym_math_function_definition,
  [sym_math_condition] = sym_math_condition,
  [sym_math_term] = sym_math_term,
  [sym_identifier_list] = sym_identifier_list,
  [sym_imperative_block] = sym_imperative_block,
  [sym_imperative_statement] = sym_imperative_statement,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [sym_string] = sym_string,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_element_repeat1] = aux_sym_element_repeat1,
  [aux_sym_element_repeat2] = aux_sym_element_repeat2,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym__math_content_repeat1] = aux_sym__math_content_repeat1,
  [aux_sym_identifier_list_repeat1] = aux_sym_identifier_list_repeat1,
  [aux_sym_imperative_block_repeat1] = aux_sym_imperative_block_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_math] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_otherwise] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_package_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_value] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym_math_block] = {
    .visible = true,
    .named = true,
  },
  [sym__math_content] = {
    .visible = false,
    .named = true,
  },
  [sym_math_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_math_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_math_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_math_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_math_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_math_term] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_list] = {
    .visible = true,
    .named = true,
  },
  [sym_imperative_block] = {
    .visible = true,
    .named = true,
  },
  [sym_imperative_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__math_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_imperative_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attribute_name = 1,
  field_attribute_value = 2,
  field_closing_tag_name = 3,
  field_key = 4,
  field_package_name = 5,
  field_tag_name = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attribute_name] = "attribute_name",
  [field_attribute_value] = "attribute_value",
  [field_closing_tag_name] = "closing_tag_name",
  [field_key] = "key",
  [field_package_name] = "package_name",
  [field_tag_name] = "tag_name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_package_name, 1},
  [1] =
    {field_attribute_name, 0},
    {field_attribute_value, 2},
  [3] =
    {field_closing_tag_name, 4},
    {field_tag_name, 1},
  [5] =
    {field_closing_tag_name, 5},
    {field_tag_name, 1},
  [7] =
    {field_key, 0},
    {field_value, 2},
  [9] =
    {field_closing_tag_name, 6},
    {field_tag_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 3,
  [10] = 7,
  [11] = 2,
  [12] = 6,
  [13] = 7,
  [14] = 3,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 17,
  [23] = 19,
  [24] = 21,
  [25] = 20,
  [26] = 26,
  [27] = 18,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 39,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 54,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 64,
  [71] = 67,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 75,
  [79] = 72,
  [80] = 80,
  [81] = 80,
  [82] = 54,
  [83] = 80,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 74,
  [97] = 97,
  [98] = 69,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 73,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 69,
  [115] = 73,
  [116] = 74,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 129,
  [132] = 132,
  [133] = 129,
  [134] = 130,
  [135] = 124,
  [136] = 136,
  [137] = 126,
  [138] = 138,
  [139] = 139,
  [140] = 136,
  [141] = 126,
  [142] = 139,
  [143] = 143,
  [144] = 139,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 124,
  [153] = 130,
  [154] = 136,
  [155] = 150,
  [156] = 150,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '"', 75,
        '\'', 79,
        '(', 46,
        ')', 47,
        '*', 53,
        '+', 55,
        ',', 38,
        '-', 56,
        '/', 54,
        ':', 42,
        ';', 45,
        '<', 33,
        '=', 36,
        '>', 34,
        '[', 37,
        ']', 39,
        'm', 9,
        'o', 26,
        'p', 7,
        'w', 17,
        '{', 40,
        '}', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 75,
        '\'', 79,
        '(', 46,
        ')', 47,
        ',', 38,
        '/', 6,
        '>', 34,
        ']', 39,
        '}', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(75);
      if (lookahead == '/') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(79);
      if (lookahead == '/') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '(', 46,
        ')', 47,
        '*', 53,
        '+', 55,
        '-', 56,
        '/', 54,
        ';', 45,
        '<', 33,
        'm', 57,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '*', 53,
        '+', 55,
        '-', 56,
        '/', 54,
        ';', 45,
        '<', 33,
        'm', 57,
        'o', 70,
        'w', 63,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(83);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'k') ADVANCE(8);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == 'w') ADVANCE(20);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(75);
      if (lookahead == '\'') ADVANCE(79);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '<') ADVANCE(32);
      if (lookahead == '[') ADVANCE(37);
      if (lookahead == 'p') ADVANCE(7);
      if (lookahead == '{') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_math);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_math);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_where);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_otherwise);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_otherwise);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(83);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(83);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(76);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(83);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(80);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 29},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 29},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 29},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 29},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 29},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 29},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 29},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 1},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 1},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 1},
  [140] = {.lex_state = 1},
  [141] = {.lex_state = 1},
  [142] = {.lex_state = 1},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 1},
  [145] = {.lex_state = 1},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 1},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 1},
  [155] = {.lex_state = 1},
  [156] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_math] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [anon_sym_otherwise] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(149),
    [sym__statement] = STATE(34),
    [sym_package_statement] = STATE(34),
    [sym_element] = STATE(34),
    [aux_sym_document_repeat1] = STATE(34),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_package] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(4), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [39] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(5), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [78] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(24), 1,
      anon_sym_LT_SLASH,
    ACTIONS(26), 1,
      anon_sym_math,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(4), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [117] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(32), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(4), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [156] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(7), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [195] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(4), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [234] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(36), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(10), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [273] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(11), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [312] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(4), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [351] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(40), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(4), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [390] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(42), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(13), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [429] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(4), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [468] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_math,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_math_expression,
    STATE(76), 1,
      sym__math_content,
    STATE(35), 2,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
    STATE(2), 5,
      sym_element,
      sym__content,
      sym_math_block,
      sym_imperative_block,
      aux_sym_element_repeat2,
  [507] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_LT_SLASH,
    ACTIONS(50), 1,
      anon_sym_SEMI,
    ACTIONS(52), 1,
      anon_sym_where,
    ACTIONS(54), 1,
      anon_sym_otherwise,
    ACTIONS(56), 1,
      anon_sym_STAR_STAR,
    STATE(51), 1,
      sym_math_condition,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(46), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [542] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_where,
    ACTIONS(54), 1,
      anon_sym_otherwise,
    ACTIONS(56), 1,
      anon_sym_STAR_STAR,
    ACTIONS(64), 1,
      anon_sym_LT_SLASH,
    ACTIONS(66), 1,
      anon_sym_SEMI,
    STATE(53), 1,
      sym_math_condition,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(62), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [577] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_STAR_STAR,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(70), 4,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 5,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_where,
      anon_sym_otherwise,
      sym_identifier,
  [601] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 5,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(72), 7,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [621] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 5,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 7,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [641] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_STAR_STAR,
    ACTIONS(70), 4,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 7,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [663] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_STAR_STAR,
    ACTIONS(70), 4,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 7,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
  [685] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_STAR_STAR,
    ACTIONS(78), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(68), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
    ACTIONS(70), 5,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [708] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 5,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(70), 6,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [727] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_STAR_STAR,
    ACTIONS(68), 5,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(70), 5,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [748] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_STAR_STAR,
    ACTIONS(68), 5,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(70), 5,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [769] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 5,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(74), 5,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [790] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 5,
      anon_sym_LT,
      anon_sym_math,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(74), 6,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [809] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_SQUOTE,
    STATE(118), 5,
      sym_element,
      sym__attribute_value,
      sym_array,
      sym_object,
      sym_string,
  [835] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_STAR_STAR,
    ACTIONS(78), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(94), 2,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
    ACTIONS(96), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(92), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [859] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_LT_SLASH,
    ACTIONS(102), 1,
      sym_identifier,
    STATE(46), 1,
      sym_math_expression,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_math,
    STATE(31), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
  [882] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_LT_SLASH,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(46), 1,
      sym_math_expression,
    ACTIONS(104), 2,
      anon_sym_LT,
      anon_sym_math,
    STATE(31), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
  [905] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_SQUOTE,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      sym_string,
    STATE(85), 1,
      sym_value,
    STATE(146), 1,
      sym_argument_list,
    ACTIONS(113), 2,
      sym_identifier,
      sym_number,
  [931] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_identifier,
    STATE(46), 1,
      sym_math_expression,
    STATE(58), 1,
      sym__math_content,
    STATE(30), 4,
      sym_math_expression_statement,
      sym_math_statement,
      sym_math_function_definition,
      aux_sym__math_content_repeat1,
  [950] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_package,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    STATE(37), 4,
      sym__statement,
      sym_package_statement,
      sym_element,
      aux_sym_document_repeat1,
  [969] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_LT_SLASH,
    ACTIONS(119), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
    STATE(36), 3,
      sym_element,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
  [986] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_LT,
    ACTIONS(126), 1,
      anon_sym_LT_SLASH,
    ACTIONS(128), 1,
      anon_sym_math,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(36), 3,
      sym_element,
      sym_imperative_statement,
      aux_sym_imperative_block_repeat1,
  [1007] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 1,
      anon_sym_package,
    ACTIONS(138), 1,
      anon_sym_LT,
    STATE(37), 4,
      sym__statement,
      sym_package_statement,
      sym_element,
      aux_sym_document_repeat1,
  [1026] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_SQUOTE,
    STATE(59), 1,
      sym_string,
    STATE(91), 1,
      sym_value,
    ACTIONS(113), 2,
      sym_identifier,
      sym_number,
  [1046] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_STAR_STAR,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    ACTIONS(78), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(96), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1064] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_SQUOTE,
    STATE(59), 1,
      sym_string,
    STATE(117), 1,
      sym_value,
    ACTIONS(113), 2,
      sym_identifier,
      sym_number,
  [1084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 6,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_identifier,
  [1096] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    ACTIONS(90), 1,
      anon_sym_SQUOTE,
    STATE(59), 1,
      sym_string,
    STATE(99), 1,
      sym_value,
    ACTIONS(113), 2,
      sym_identifier,
      sym_number,
  [1116] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_STAR_STAR,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    ACTIONS(78), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(96), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 6,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      sym_identifier,
  [1146] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
    ACTIONS(149), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1159] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_LT_SLASH,
    ACTIONS(157), 1,
      anon_sym_SEMI,
    ACTIONS(153), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1174] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(163), 1,
      sym_number,
    STATE(29), 1,
      sym_math_term,
    STATE(49), 1,
      sym_function_call,
  [1193] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
    ACTIONS(165), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1206] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_LT_SLASH,
    ACTIONS(173), 1,
      anon_sym_SEMI,
    ACTIONS(169), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1221] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
    ACTIONS(175), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1234] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_LT_SLASH,
    ACTIONS(183), 1,
      anon_sym_SEMI,
    ACTIONS(179), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1249] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_LT_SLASH,
      anon_sym_SEMI,
    ACTIONS(185), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1262] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_LT_SLASH,
    ACTIONS(193), 1,
      anon_sym_SEMI,
    ACTIONS(189), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1277] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_GT,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(57), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [1291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_LT_SLASH,
    ACTIONS(199), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1303] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym_math_term,
    ACTIONS(205), 2,
      sym_identifier,
      sym_number,
  [1317] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_GT,
    ACTIONS(209), 1,
      sym_identifier,
    STATE(57), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [1331] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LT_SLASH,
    ACTIONS(212), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [1353] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_LT_SLASH,
    ACTIONS(218), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1365] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(222), 1,
      anon_sym_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [1379] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym_math_term,
    ACTIONS(205), 2,
      sym_identifier,
      sym_number,
  [1393] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(63), 1,
      aux_sym_array_repeat1,
    ACTIONS(227), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1407] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_math_term,
    ACTIONS(163), 2,
      sym_identifier,
      sym_number,
  [1421] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_LT_SLASH,
    ACTIONS(189), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1433] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    ACTIONS(229), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1445] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(24), 1,
      sym_math_term,
    ACTIONS(163), 2,
      sym_identifier,
      sym_number,
  [1459] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_LT_SLASH,
    ACTIONS(233), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1471] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_LT_SLASH,
    ACTIONS(237), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1483] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_math_term,
    ACTIONS(205), 2,
      sym_identifier,
      sym_number,
  [1497] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_math_term,
    ACTIONS(205), 2,
      sym_identifier,
      sym_number,
  [1511] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
    STATE(17), 1,
      sym_math_term,
    ACTIONS(205), 2,
      sym_identifier,
      sym_number,
  [1525] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_LT_SLASH,
    ACTIONS(241), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1537] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    ACTIONS(245), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1549] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(43), 1,
      sym_math_term,
    ACTIONS(163), 2,
      sym_identifier,
      sym_number,
  [1563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LT_SLASH,
    ACTIONS(249), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1575] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(29), 1,
      sym_math_term,
    ACTIONS(163), 2,
      sym_identifier,
      sym_number,
  [1589] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(39), 1,
      sym_math_term,
    ACTIONS(163), 2,
      sym_identifier,
      sym_number,
  [1603] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_math_term,
    ACTIONS(163), 2,
      sym_identifier,
      sym_number,
  [1617] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(253), 1,
      anon_sym_GT,
    STATE(61), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [1631] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(255), 1,
      anon_sym_GT,
    STATE(82), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [1645] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(257), 1,
      anon_sym_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [1659] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(259), 1,
      anon_sym_GT,
    STATE(54), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [1673] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LT_SLASH,
    ACTIONS(62), 3,
      anon_sym_LT,
      anon_sym_math,
      sym_identifier,
  [1685] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      aux_sym_array_repeat1,
  [1698] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    ACTIONS(267), 1,
      sym_identifier,
    STATE(151), 1,
      sym_identifier_list,
  [1711] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RBRACK,
    STATE(63), 1,
      aux_sym_array_repeat1,
  [1724] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    ACTIONS(273), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      aux_sym_object_repeat1,
  [1737] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_identifier_list_repeat1,
  [1750] = 4,
    ACTIONS(280), 1,
      anon_sym_DQUOTE,
    ACTIONS(282), 1,
      aux_sym_string_token1,
    ACTIONS(285), 1,
      sym_comment,
    STATE(90), 1,
      aux_sym_string_repeat1,
  [1763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1772] = 4,
    ACTIONS(285), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_SQUOTE,
    ACTIONS(289), 1,
      aux_sym_string_token2,
    STATE(92), 1,
      aux_sym_string_repeat2,
  [1785] = 4,
    ACTIONS(285), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_DQUOTE,
    ACTIONS(294), 1,
      aux_sym_string_token1,
    STATE(103), 1,
      aux_sym_string_repeat1,
  [1798] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      aux_sym_object_repeat1,
  [1811] = 4,
    ACTIONS(285), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_SQUOTE,
    ACTIONS(301), 1,
      aux_sym_string_token2,
    STATE(104), 1,
      aux_sym_string_repeat2,
  [1824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 3,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_LT,
  [1833] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_array_repeat1,
  [1846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 3,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_LT,
  [1855] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_RBRACK,
    STATE(87), 1,
      aux_sym_array_repeat1,
  [1868] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    STATE(106), 1,
      aux_sym_identifier_list_repeat1,
  [1881] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RBRACE,
    STATE(88), 1,
      aux_sym_object_repeat1,
  [1894] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 3,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_LT,
  [1903] = 4,
    ACTIONS(285), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_DQUOTE,
    ACTIONS(317), 1,
      aux_sym_string_token1,
    STATE(90), 1,
      aux_sym_string_repeat1,
  [1916] = 4,
    ACTIONS(285), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_SQUOTE,
    ACTIONS(319), 1,
      aux_sym_string_token2,
    STATE(92), 1,
      aux_sym_string_repeat2,
  [1929] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 3,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_LT,
  [1938] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(321), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_identifier_list_repeat1,
  [1951] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      sym_identifier,
    STATE(52), 1,
      sym_math_expression,
  [1961] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_EQ,
    ACTIONS(327), 1,
      anon_sym_LPAREN,
  [1971] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 2,
      anon_sym_GT,
      sym_identifier,
  [1987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_LPAREN,
    ACTIONS(331), 1,
      anon_sym_EQ,
  [1997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_identifier,
    STATE(101), 1,
      sym_pair,
  [2007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 2,
      anon_sym_GT,
      sym_identifier,
  [2015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      anon_sym_GT,
      sym_identifier,
  [2023] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      anon_sym_GT,
      sym_identifier,
  [2031] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      anon_sym_GT,
      sym_identifier,
  [2039] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 2,
      anon_sym_GT,
      sym_identifier,
  [2055] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2063] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 2,
      anon_sym_GT,
      sym_identifier,
  [2071] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_identifier,
    STATE(119), 1,
      sym_pair,
  [2081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 2,
      anon_sym_GT,
      sym_identifier,
  [2089] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      sym_identifier,
    STATE(49), 1,
      sym_function_call,
  [2099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_GT,
  [2106] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_EQ,
  [2113] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      sym_identifier,
  [2120] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_EQ,
  [2127] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
  [2134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_GT,
  [2141] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_GT,
  [2148] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_GT,
  [2155] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_EQ,
  [2162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_GT,
  [2169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      anon_sym_GT,
  [2176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_GT,
  [2183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym_identifier,
  [2190] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      sym_identifier,
  [2197] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      sym_identifier,
  [2204] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      sym_identifier,
  [2211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      sym_identifier,
  [2218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      sym_identifier,
  [2225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      sym_identifier,
  [2232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      anon_sym_EQ,
  [2239] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      sym_identifier,
  [2246] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 1,
      sym_identifier,
  [2253] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_RPAREN,
  [2260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 1,
      anon_sym_EQ,
  [2267] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_COLON,
  [2274] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      ts_builtin_sym_end,
  [2281] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      sym_identifier,
  [2288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      anon_sym_RPAREN,
  [2295] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      anon_sym_GT,
  [2302] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      anon_sym_GT,
  [2309] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      sym_identifier,
  [2316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      sym_identifier,
  [2323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 195,
  [SMALL_STATE(8)] = 234,
  [SMALL_STATE(9)] = 273,
  [SMALL_STATE(10)] = 312,
  [SMALL_STATE(11)] = 351,
  [SMALL_STATE(12)] = 390,
  [SMALL_STATE(13)] = 429,
  [SMALL_STATE(14)] = 468,
  [SMALL_STATE(15)] = 507,
  [SMALL_STATE(16)] = 542,
  [SMALL_STATE(17)] = 577,
  [SMALL_STATE(18)] = 601,
  [SMALL_STATE(19)] = 621,
  [SMALL_STATE(20)] = 641,
  [SMALL_STATE(21)] = 663,
  [SMALL_STATE(22)] = 685,
  [SMALL_STATE(23)] = 708,
  [SMALL_STATE(24)] = 727,
  [SMALL_STATE(25)] = 748,
  [SMALL_STATE(26)] = 769,
  [SMALL_STATE(27)] = 790,
  [SMALL_STATE(28)] = 809,
  [SMALL_STATE(29)] = 835,
  [SMALL_STATE(30)] = 859,
  [SMALL_STATE(31)] = 882,
  [SMALL_STATE(32)] = 905,
  [SMALL_STATE(33)] = 931,
  [SMALL_STATE(34)] = 950,
  [SMALL_STATE(35)] = 969,
  [SMALL_STATE(36)] = 986,
  [SMALL_STATE(37)] = 1007,
  [SMALL_STATE(38)] = 1026,
  [SMALL_STATE(39)] = 1046,
  [SMALL_STATE(40)] = 1064,
  [SMALL_STATE(41)] = 1084,
  [SMALL_STATE(42)] = 1096,
  [SMALL_STATE(43)] = 1116,
  [SMALL_STATE(44)] = 1134,
  [SMALL_STATE(45)] = 1146,
  [SMALL_STATE(46)] = 1159,
  [SMALL_STATE(47)] = 1174,
  [SMALL_STATE(48)] = 1193,
  [SMALL_STATE(49)] = 1206,
  [SMALL_STATE(50)] = 1221,
  [SMALL_STATE(51)] = 1234,
  [SMALL_STATE(52)] = 1249,
  [SMALL_STATE(53)] = 1262,
  [SMALL_STATE(54)] = 1277,
  [SMALL_STATE(55)] = 1291,
  [SMALL_STATE(56)] = 1303,
  [SMALL_STATE(57)] = 1317,
  [SMALL_STATE(58)] = 1331,
  [SMALL_STATE(59)] = 1343,
  [SMALL_STATE(60)] = 1353,
  [SMALL_STATE(61)] = 1365,
  [SMALL_STATE(62)] = 1379,
  [SMALL_STATE(63)] = 1393,
  [SMALL_STATE(64)] = 1407,
  [SMALL_STATE(65)] = 1421,
  [SMALL_STATE(66)] = 1433,
  [SMALL_STATE(67)] = 1445,
  [SMALL_STATE(68)] = 1459,
  [SMALL_STATE(69)] = 1471,
  [SMALL_STATE(70)] = 1483,
  [SMALL_STATE(71)] = 1497,
  [SMALL_STATE(72)] = 1511,
  [SMALL_STATE(73)] = 1525,
  [SMALL_STATE(74)] = 1537,
  [SMALL_STATE(75)] = 1549,
  [SMALL_STATE(76)] = 1563,
  [SMALL_STATE(77)] = 1575,
  [SMALL_STATE(78)] = 1589,
  [SMALL_STATE(79)] = 1603,
  [SMALL_STATE(80)] = 1617,
  [SMALL_STATE(81)] = 1631,
  [SMALL_STATE(82)] = 1645,
  [SMALL_STATE(83)] = 1659,
  [SMALL_STATE(84)] = 1673,
  [SMALL_STATE(85)] = 1685,
  [SMALL_STATE(86)] = 1698,
  [SMALL_STATE(87)] = 1711,
  [SMALL_STATE(88)] = 1724,
  [SMALL_STATE(89)] = 1737,
  [SMALL_STATE(90)] = 1750,
  [SMALL_STATE(91)] = 1763,
  [SMALL_STATE(92)] = 1772,
  [SMALL_STATE(93)] = 1785,
  [SMALL_STATE(94)] = 1798,
  [SMALL_STATE(95)] = 1811,
  [SMALL_STATE(96)] = 1824,
  [SMALL_STATE(97)] = 1833,
  [SMALL_STATE(98)] = 1846,
  [SMALL_STATE(99)] = 1855,
  [SMALL_STATE(100)] = 1868,
  [SMALL_STATE(101)] = 1881,
  [SMALL_STATE(102)] = 1894,
  [SMALL_STATE(103)] = 1903,
  [SMALL_STATE(104)] = 1916,
  [SMALL_STATE(105)] = 1929,
  [SMALL_STATE(106)] = 1938,
  [SMALL_STATE(107)] = 1951,
  [SMALL_STATE(108)] = 1961,
  [SMALL_STATE(109)] = 1971,
  [SMALL_STATE(110)] = 1979,
  [SMALL_STATE(111)] = 1987,
  [SMALL_STATE(112)] = 1997,
  [SMALL_STATE(113)] = 2007,
  [SMALL_STATE(114)] = 2015,
  [SMALL_STATE(115)] = 2023,
  [SMALL_STATE(116)] = 2031,
  [SMALL_STATE(117)] = 2039,
  [SMALL_STATE(118)] = 2047,
  [SMALL_STATE(119)] = 2055,
  [SMALL_STATE(120)] = 2063,
  [SMALL_STATE(121)] = 2071,
  [SMALL_STATE(122)] = 2081,
  [SMALL_STATE(123)] = 2089,
  [SMALL_STATE(124)] = 2099,
  [SMALL_STATE(125)] = 2106,
  [SMALL_STATE(126)] = 2113,
  [SMALL_STATE(127)] = 2120,
  [SMALL_STATE(128)] = 2127,
  [SMALL_STATE(129)] = 2134,
  [SMALL_STATE(130)] = 2141,
  [SMALL_STATE(131)] = 2148,
  [SMALL_STATE(132)] = 2155,
  [SMALL_STATE(133)] = 2162,
  [SMALL_STATE(134)] = 2169,
  [SMALL_STATE(135)] = 2176,
  [SMALL_STATE(136)] = 2183,
  [SMALL_STATE(137)] = 2190,
  [SMALL_STATE(138)] = 2197,
  [SMALL_STATE(139)] = 2204,
  [SMALL_STATE(140)] = 2211,
  [SMALL_STATE(141)] = 2218,
  [SMALL_STATE(142)] = 2225,
  [SMALL_STATE(143)] = 2232,
  [SMALL_STATE(144)] = 2239,
  [SMALL_STATE(145)] = 2246,
  [SMALL_STATE(146)] = 2253,
  [SMALL_STATE(147)] = 2260,
  [SMALL_STATE(148)] = 2267,
  [SMALL_STATE(149)] = 2274,
  [SMALL_STATE(150)] = 2281,
  [SMALL_STATE(151)] = 2288,
  [SMALL_STATE(152)] = 2295,
  [SMALL_STATE(153)] = 2302,
  [SMALL_STATE(154)] = 2309,
  [SMALL_STATE(155)] = 2316,
  [SMALL_STATE(156)] = 2323,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(155),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0), SHIFT_REPEAT(155),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0), SHIFT_REPEAT(33),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0), SHIFT_REPEAT(111),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_function_definition, 5, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_function_definition, 5, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_function_definition, 6, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_function_definition, 6, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_term, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_term, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_term, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_term, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_expression, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_expression, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__math_content, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__math_content, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__math_content_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__math_content_repeat1, 2, 0, 0),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__math_content_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_imperative_block, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imperative_block, 1, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_imperative_block_repeat1, 2, 0, 0), SHIFT_REPEAT(155),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_imperative_block_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_imperative_block_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_imperative_block_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(145),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(150),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_expression_statement, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_expression_statement, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_imperative_statement, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imperative_statement, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_condition, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_condition, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_statement, 6, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_statement, 6, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_condition, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_condition, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_statement, 7, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_statement, 7, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_imperative_statement, 4, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imperative_statement, 4, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(143),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_block, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_block, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_expression_statement, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_expression_statement, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_function_definition, 7, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_function_definition, 7, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_statement, 8, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_statement, 8, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 6, 0, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 6, 0, 3),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 7, 0, 4),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 7, 0, 4),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 8, 0, 6),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 8, 0, 6),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_block, 1, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_block, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0), SHIFT_REPEAT(138),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [289] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(92),
  [292] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 1, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_statement, 2, 0, 1),
  [315] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [317] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 2, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 5),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 2),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [393] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cxml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
