#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  anon_sym_package = 1,
  anon_sym_LT = 2,
  anon_sym_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_EQ = 5,
  anon_sym_LBRACK = 6,
  anon_sym_COMMA = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COLON = 11,
  anon_sym_LTmath_GT = 12,
  anon_sym_LT_SLASHmath_GT = 13,
  anon_sym_LT_EQ = 14,
  anon_sym_GT_EQ = 15,
  anon_sym_EQ_EQ = 16,
  anon_sym_BANG_EQ = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_SEMI = 20,
  anon_sym_where = 21,
  anon_sym_otherwise = 22,
  anon_sym_STAR_STAR = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  anon_sym_PLUS = 26,
  anon_sym_DASH = 27,
  sym_identifier = 28,
  sym_number = 29,
  anon_sym_DQUOTE = 30,
  aux_sym_string_token1 = 31,
  anon_sym_SQUOTE = 32,
  aux_sym_string_token2 = 33,
  sym_comment = 34,
  sym_document = 35,
  sym__statement = 36,
  sym_package_statement = 37,
  sym_element = 38,
  sym_attribute = 39,
  sym__attribute_value = 40,
  sym_array = 41,
  sym_object = 42,
  sym_pair = 43,
  sym_value = 44,
  sym__content = 45,
  sym_math_block = 46,
  sym__math_content = 47,
  sym_cond_expression = 48,
  sym_math_statement = 49,
  sym_math_condition = 50,
  sym_math_term = 51,
  sym_identifier_list = 52,
  sym_string = 53,
  aux_sym_document_repeat1 = 54,
  aux_sym_element_repeat1 = 55,
  aux_sym_element_repeat2 = 56,
  aux_sym_array_repeat1 = 57,
  aux_sym_object_repeat1 = 58,
  aux_sym__math_content_repeat1 = 59,
  aux_sym_identifier_list_repeat1 = 60,
  aux_sym_string_repeat1 = 61,
  aux_sym_string_repeat2 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_package] = "package",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_LTmath_GT] = "<math>",
  [anon_sym_LT_SLASHmath_GT] = "</math>",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SEMI] = ";",
  [anon_sym_where] = "where",
  [anon_sym_otherwise] = "otherwise",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__statement] = "_statement",
  [sym_package_statement] = "package_statement",
  [sym_element] = "element",
  [sym_attribute] = "attribute",
  [sym__attribute_value] = "_attribute_value",
  [sym_array] = "array",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym_value] = "value",
  [sym__content] = "_content",
  [sym_math_block] = "math_block",
  [sym__math_content] = "_math_content",
  [sym_cond_expression] = "cond_expression",
  [sym_math_statement] = "math_statement",
  [sym_math_condition] = "math_condition",
  [sym_math_term] = "math_term",
  [sym_identifier_list] = "identifier_list",
  [sym_string] = "string",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_element_repeat1] = "element_repeat1",
  [aux_sym_element_repeat2] = "element_repeat2",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym__math_content_repeat1] = "_math_content_repeat1",
  [aux_sym_identifier_list_repeat1] = "identifier_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LTmath_GT] = anon_sym_LTmath_GT,
  [anon_sym_LT_SLASHmath_GT] = anon_sym_LT_SLASHmath_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_where] = anon_sym_where,
  [anon_sym_otherwise] = anon_sym_otherwise,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__statement] = sym__statement,
  [sym_package_statement] = sym_package_statement,
  [sym_element] = sym_element,
  [sym_attribute] = sym_attribute,
  [sym__attribute_value] = sym__attribute_value,
  [sym_array] = sym_array,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym_value] = sym_value,
  [sym__content] = sym__content,
  [sym_math_block] = sym_math_block,
  [sym__math_content] = sym__math_content,
  [sym_cond_expression] = sym_cond_expression,
  [sym_math_statement] = sym_math_statement,
  [sym_math_condition] = sym_math_condition,
  [sym_math_term] = sym_math_term,
  [sym_identifier_list] = sym_identifier_list,
  [sym_string] = sym_string,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_element_repeat1] = aux_sym_element_repeat1,
  [aux_sym_element_repeat2] = aux_sym_element_repeat2,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym__math_content_repeat1] = aux_sym__math_content_repeat1,
  [aux_sym_identifier_list_repeat1] = aux_sym_identifier_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTmath_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHmath_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_otherwise] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_package_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_value] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym_math_block] = {
    .visible = true,
    .named = true,
  },
  [sym__math_content] = {
    .visible = false,
    .named = true,
  },
  [sym_cond_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_math_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_math_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_math_term] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__math_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attribute_name = 1,
  field_attribute_value = 2,
  field_closing_tag_name = 3,
  field_key = 4,
  field_package_name = 5,
  field_tag_name = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attribute_name] = "attribute_name",
  [field_attribute_value] = "attribute_value",
  [field_closing_tag_name] = "closing_tag_name",
  [field_key] = "key",
  [field_package_name] = "package_name",
  [field_tag_name] = "tag_name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_package_name, 1},
  [1] =
    {field_attribute_name, 0},
    {field_attribute_value, 2},
  [3] =
    {field_closing_tag_name, 4},
    {field_tag_name, 1},
  [5] =
    {field_closing_tag_name, 5},
    {field_tag_name, 1},
  [7] =
    {field_key, 0},
    {field_value, 2},
  [9] =
    {field_closing_tag_name, 6},
    {field_tag_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 13,
  [18] = 15,
  [19] = 12,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 39,
  [44] = 31,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 28,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 26,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 29,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 88,
  [99] = 86,
  [100] = 93,
  [101] = 89,
  [102] = 102,
  [103] = 103,
  [104] = 102,
  [105] = 105,
  [106] = 103,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 105,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      ADVANCE_MAP(
        '!', 7,
        '"', 74,
        '\'', 78,
        '(', 61,
        ')', 62,
        '*', 67,
        '+', 69,
        ',', 50,
        '-', 70,
        '/', 68,
        ':', 54,
        ';', 63,
        '<', 42,
        '=', 48,
        '>', 45,
        '[', 49,
        ']', 51,
        'o', 35,
        'p', 12,
        'w', 23,
        '{', 52,
        '}', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ';') ADVANCE(63);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '>') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 74,
        '\'', 78,
        '(', 61,
        ')', 62,
        ',', 50,
        '/', 5,
        '<', 43,
        '>', 44,
        ']', 51,
        '}', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '/') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(78);
      if (lookahead == '/') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0) ADVANCE(79);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(82);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(60);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(58);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(55);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(56);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'g') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'h') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(11);
      END_STATE();
    case 26:
      if (lookahead == 'h') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'k') ADVANCE(13);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 36:
      if (lookahead == 'w') ADVANCE(27);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 38:
      if (eof) ADVANCE(39);
      ADVANCE_MAP(
        '"', 74,
        '\'', 78,
        '/', 5,
        '<', 41,
        '=', 47,
        '>', 44,
        '[', 49,
        'p', 12,
        '{', 52,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == '=') ADVANCE(57);
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(58);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LTmath_GT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LT_SLASHmath_GT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_otherwise);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(82);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(82);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(75);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(79);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(82);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 38},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 38},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 38},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 38},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 38},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 38},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 38},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 38},
  [87] = {.lex_state = 38},
  [88] = {.lex_state = 38},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 38},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 38},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 38},
  [99] = {.lex_state = 38},
  [100] = {.lex_state = 38},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 38},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LTmath_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [anon_sym_otherwise] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(108),
    [sym__statement] = STATE(10),
    [sym_package_statement] = STATE(10),
    [sym_element] = STATE(10),
    [aux_sym_document_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_package] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(76), 5,
      sym_element,
      sym__attribute_value,
      sym_array,
      sym_object,
      sym_string,
  [26] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_STAR_STAR,
    ACTIONS(25), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(21), 5,
      anon_sym_RPAREN,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_PLUS,
      anon_sym_DASH,
  [44] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(27), 6,
      anon_sym_RPAREN,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [60] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_STAR_STAR,
    ACTIONS(31), 1,
      anon_sym_where,
    ACTIONS(33), 1,
      anon_sym_otherwise,
    STATE(59), 1,
      sym_math_condition,
    ACTIONS(25), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [84] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_STAR_STAR,
    ACTIONS(31), 1,
      anon_sym_where,
    ACTIONS(33), 1,
      anon_sym_otherwise,
    STATE(45), 1,
      sym_math_condition,
    ACTIONS(25), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [108] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(21), 6,
      anon_sym_RPAREN,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [124] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_STAR_STAR,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(21), 5,
      anon_sym_RPAREN,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_PLUS,
      anon_sym_DASH,
  [142] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_STAR_STAR,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(21), 5,
      anon_sym_RPAREN,
      anon_sym_where,
      anon_sym_otherwise,
      anon_sym_PLUS,
      anon_sym_DASH,
  [160] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_package,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(20), 4,
      sym__statement,
      sym_package_statement,
      sym_element,
      aux_sym_document_repeat1,
  [179] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LT,
    ACTIONS(44), 1,
      anon_sym_LT_SLASH,
    ACTIONS(46), 1,
      anon_sym_LTmath_GT,
    STATE(11), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [198] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      anon_sym_LT_SLASH,
    ACTIONS(53), 1,
      anon_sym_LTmath_GT,
    STATE(11), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [217] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      anon_sym_LTmath_GT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    STATE(11), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [236] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      anon_sym_LTmath_GT,
    ACTIONS(57), 1,
      anon_sym_LT_SLASH,
    STATE(13), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [255] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      anon_sym_LTmath_GT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    STATE(12), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [274] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      anon_sym_LTmath_GT,
    ACTIONS(59), 1,
      anon_sym_LT_SLASH,
    STATE(17), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [293] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      anon_sym_LTmath_GT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH,
    STATE(11), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [312] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      anon_sym_LTmath_GT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH,
    STATE(19), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [331] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      anon_sym_LTmath_GT,
    ACTIONS(63), 1,
      anon_sym_LT_SLASH,
    STATE(11), 4,
      sym_element,
      sym__content,
      sym_math_block,
      aux_sym_element_repeat2,
  [350] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      anon_sym_package,
    ACTIONS(70), 1,
      anon_sym_LT,
    STATE(20), 4,
      sym__statement,
      sym_package_statement,
      sym_element,
      aux_sym_document_repeat1,
  [369] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_STAR_STAR,
    ACTIONS(73), 1,
      anon_sym_RPAREN,
    ACTIONS(25), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [387] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      sym_string,
    STATE(65), 1,
      sym_value,
    ACTIONS(75), 2,
      sym_identifier,
      sym_number,
  [407] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      sym_string,
    STATE(81), 1,
      sym_value,
    ACTIONS(75), 2,
      sym_identifier,
      sym_number,
  [427] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      sym_string,
    STATE(78), 1,
      sym_value,
    ACTIONS(75), 2,
      sym_identifier,
      sym_number,
  [447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 5,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_identifier,
  [458] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_LT,
    ACTIONS(81), 4,
      anon_sym_GT,
      anon_sym_LT_SLASH,
      anon_sym_LTmath_GT,
      sym_identifier,
  [471] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 5,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_identifier,
  [482] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(87), 4,
      anon_sym_GT,
      anon_sym_LT_SLASH,
      anon_sym_LTmath_GT,
      sym_identifier,
  [495] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LT,
    ACTIONS(91), 4,
      anon_sym_GT,
      anon_sym_LT_SLASH,
      anon_sym_LTmath_GT,
      sym_identifier,
  [508] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_math_term,
    ACTIONS(95), 2,
      sym_identifier,
      sym_number,
  [522] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_GT,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(41), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [536] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym_identifier,
    STATE(96), 1,
      sym__math_content,
    STATE(40), 2,
      sym_math_statement,
      aux_sym__math_content_repeat1,
  [550] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_math_term,
    ACTIONS(95), 2,
      sym_identifier,
      sym_number,
  [564] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_math_term,
    ACTIONS(95), 2,
      sym_identifier,
      sym_number,
  [578] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    STATE(3), 1,
      sym_math_term,
    ACTIONS(95), 2,
      sym_identifier,
      sym_number,
  [592] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      sym_math_term,
    ACTIONS(95), 2,
      sym_identifier,
      sym_number,
  [606] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LT_SLASHmath_GT,
    ACTIONS(105), 1,
      sym_identifier,
    STATE(37), 2,
      sym_math_statement,
      aux_sym__math_content_repeat1,
  [620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 4,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [630] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(110), 1,
      anon_sym_GT,
    STATE(31), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [644] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(112), 1,
      anon_sym_LT_SLASHmath_GT,
    STATE(37), 2,
      sym_math_statement,
      aux_sym__math_content_repeat1,
  [658] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_GT,
    ACTIONS(116), 1,
      sym_identifier,
    STATE(41), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [672] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    STATE(5), 1,
      sym_math_term,
    ACTIONS(95), 2,
      sym_identifier,
      sym_number,
  [686] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_GT,
    STATE(44), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [700] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_GT,
    STATE(41), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [714] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_SEMI,
    ACTIONS(123), 2,
      anon_sym_LT_SLASHmath_GT,
      sym_identifier,
  [725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_identifier_list_repeat1,
  [738] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(133), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_array_repeat1,
  [751] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      aux_sym_object_repeat1,
  [764] = 4,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(141), 1,
      aux_sym_string_token1,
    ACTIONS(144), 1,
      sym_comment,
    STATE(49), 1,
      aux_sym_string_repeat1,
  [777] = 4,
    ACTIONS(144), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_SQUOTE,
    ACTIONS(148), 1,
      aux_sym_string_token2,
    STATE(50), 1,
      aux_sym_string_repeat2,
  [790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_identifier_list_repeat1,
  [803] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_array_repeat1,
  [816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      aux_sym_object_repeat1,
  [829] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 3,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_LT,
  [838] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_identifier_list_repeat1,
  [851] = 4,
    ACTIONS(144), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      aux_sym_string_token1,
    STATE(69), 1,
      aux_sym_string_repeat1,
  [864] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 3,
      anon_sym_LT_SLASHmath_GT,
      anon_sym_SEMI,
      sym_identifier,
  [873] = 4,
    ACTIONS(144), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_SQUOTE,
    ACTIONS(174), 1,
      aux_sym_string_token2,
    STATE(70), 1,
      aux_sym_string_repeat2,
  [886] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_SEMI,
    ACTIONS(176), 2,
      anon_sym_LT_SLASHmath_GT,
      sym_identifier,
  [897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_LT,
  [906] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    ACTIONS(182), 1,
      sym_identifier,
    STATE(109), 1,
      sym_identifier_list,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_LT,
    ACTIONS(186), 2,
      anon_sym_LT_SLASH,
      anon_sym_LTmath_GT,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 3,
      anon_sym_LT_SLASHmath_GT,
      anon_sym_SEMI,
      sym_identifier,
  [939] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [948] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RBRACK,
    STATE(47), 1,
      aux_sym_array_repeat1,
  [961] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 3,
      anon_sym_LT_SLASHmath_GT,
      anon_sym_SEMI,
      sym_identifier,
  [970] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      aux_sym_object_repeat1,
  [983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 3,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_LT,
  [992] = 4,
    ACTIONS(144), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_DQUOTE,
    ACTIONS(202), 1,
      aux_sym_string_token1,
    STATE(49), 1,
      aux_sym_string_repeat1,
  [1005] = 4,
    ACTIONS(144), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_SQUOTE,
    ACTIONS(204), 1,
      aux_sym_string_token2,
    STATE(50), 1,
      aux_sym_string_repeat2,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_LT,
  [1027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1035] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_identifier,
    STATE(83), 1,
      sym_pair,
  [1045] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_identifier,
    STATE(67), 1,
      sym_pair,
  [1055] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(63), 1,
      sym_cond_expression,
  [1065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 2,
      anon_sym_GT,
      sym_identifier,
  [1073] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 2,
      anon_sym_GT,
      sym_identifier,
  [1081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1089] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      anon_sym_GT,
      sym_identifier,
  [1097] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 2,
      anon_sym_GT,
      sym_identifier,
  [1105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1113] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_LT_SLASHmath_GT,
      sym_identifier,
  [1121] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1129] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 2,
      anon_sym_LT_SLASHmath_GT,
      sym_identifier,
  [1137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 2,
      anon_sym_GT,
      sym_identifier,
  [1145] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_GT,
  [1152] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_EQ,
  [1159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_GT,
  [1166] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_identifier,
  [1173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_EQ,
  [1180] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_identifier,
  [1187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_identifier,
  [1194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_GT,
  [1201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_identifier,
  [1208] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_COLON,
  [1215] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LT_SLASHmath_GT,
  [1222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LPAREN,
  [1229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_GT,
  [1236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_GT,
  [1243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_GT,
  [1250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
  [1257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_identifier,
  [1264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      sym_identifier,
  [1278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_identifier,
  [1285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
  [1292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_EQ,
  [1299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
  [1306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
  [1313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 108,
  [SMALL_STATE(8)] = 124,
  [SMALL_STATE(9)] = 142,
  [SMALL_STATE(10)] = 160,
  [SMALL_STATE(11)] = 179,
  [SMALL_STATE(12)] = 198,
  [SMALL_STATE(13)] = 217,
  [SMALL_STATE(14)] = 236,
  [SMALL_STATE(15)] = 255,
  [SMALL_STATE(16)] = 274,
  [SMALL_STATE(17)] = 293,
  [SMALL_STATE(18)] = 312,
  [SMALL_STATE(19)] = 331,
  [SMALL_STATE(20)] = 350,
  [SMALL_STATE(21)] = 369,
  [SMALL_STATE(22)] = 387,
  [SMALL_STATE(23)] = 407,
  [SMALL_STATE(24)] = 427,
  [SMALL_STATE(25)] = 447,
  [SMALL_STATE(26)] = 458,
  [SMALL_STATE(27)] = 471,
  [SMALL_STATE(28)] = 482,
  [SMALL_STATE(29)] = 495,
  [SMALL_STATE(30)] = 508,
  [SMALL_STATE(31)] = 522,
  [SMALL_STATE(32)] = 536,
  [SMALL_STATE(33)] = 550,
  [SMALL_STATE(34)] = 564,
  [SMALL_STATE(35)] = 578,
  [SMALL_STATE(36)] = 592,
  [SMALL_STATE(37)] = 606,
  [SMALL_STATE(38)] = 620,
  [SMALL_STATE(39)] = 630,
  [SMALL_STATE(40)] = 644,
  [SMALL_STATE(41)] = 658,
  [SMALL_STATE(42)] = 672,
  [SMALL_STATE(43)] = 686,
  [SMALL_STATE(44)] = 700,
  [SMALL_STATE(45)] = 714,
  [SMALL_STATE(46)] = 725,
  [SMALL_STATE(47)] = 738,
  [SMALL_STATE(48)] = 751,
  [SMALL_STATE(49)] = 764,
  [SMALL_STATE(50)] = 777,
  [SMALL_STATE(51)] = 790,
  [SMALL_STATE(52)] = 803,
  [SMALL_STATE(53)] = 816,
  [SMALL_STATE(54)] = 829,
  [SMALL_STATE(55)] = 838,
  [SMALL_STATE(56)] = 851,
  [SMALL_STATE(57)] = 864,
  [SMALL_STATE(58)] = 873,
  [SMALL_STATE(59)] = 886,
  [SMALL_STATE(60)] = 897,
  [SMALL_STATE(61)] = 906,
  [SMALL_STATE(62)] = 919,
  [SMALL_STATE(63)] = 930,
  [SMALL_STATE(64)] = 939,
  [SMALL_STATE(65)] = 948,
  [SMALL_STATE(66)] = 961,
  [SMALL_STATE(67)] = 970,
  [SMALL_STATE(68)] = 983,
  [SMALL_STATE(69)] = 992,
  [SMALL_STATE(70)] = 1005,
  [SMALL_STATE(71)] = 1018,
  [SMALL_STATE(72)] = 1027,
  [SMALL_STATE(73)] = 1035,
  [SMALL_STATE(74)] = 1045,
  [SMALL_STATE(75)] = 1055,
  [SMALL_STATE(76)] = 1065,
  [SMALL_STATE(77)] = 1073,
  [SMALL_STATE(78)] = 1081,
  [SMALL_STATE(79)] = 1089,
  [SMALL_STATE(80)] = 1097,
  [SMALL_STATE(81)] = 1105,
  [SMALL_STATE(82)] = 1113,
  [SMALL_STATE(83)] = 1121,
  [SMALL_STATE(84)] = 1129,
  [SMALL_STATE(85)] = 1137,
  [SMALL_STATE(86)] = 1145,
  [SMALL_STATE(87)] = 1152,
  [SMALL_STATE(88)] = 1159,
  [SMALL_STATE(89)] = 1166,
  [SMALL_STATE(90)] = 1173,
  [SMALL_STATE(91)] = 1180,
  [SMALL_STATE(92)] = 1187,
  [SMALL_STATE(93)] = 1194,
  [SMALL_STATE(94)] = 1201,
  [SMALL_STATE(95)] = 1208,
  [SMALL_STATE(96)] = 1215,
  [SMALL_STATE(97)] = 1222,
  [SMALL_STATE(98)] = 1229,
  [SMALL_STATE(99)] = 1236,
  [SMALL_STATE(100)] = 1243,
  [SMALL_STATE(101)] = 1250,
  [SMALL_STATE(102)] = 1257,
  [SMALL_STATE(103)] = 1264,
  [SMALL_STATE(104)] = 1271,
  [SMALL_STATE(105)] = 1278,
  [SMALL_STATE(106)] = 1285,
  [SMALL_STATE(107)] = 1292,
  [SMALL_STATE(108)] = 1299,
  [SMALL_STATE(109)] = 1306,
  [SMALL_STATE(110)] = 1313,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_term, 3, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_term, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_term, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_term, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0), SHIFT_REPEAT(110),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0), SHIFT_REPEAT(32),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 6, 0, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 6, 0, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 8, 0, 6),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 8, 0, 6),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 7, 0, 4),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 7, 0, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__math_content_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__math_content_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__math_content, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_statement, 7, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(50),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 2, 0, 0),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_condition, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_statement, 6, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_block, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_block, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_condition, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond_expression, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_statement, 2, 0, 1),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 5),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_statement, 8, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [268] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cxml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
